---
name: vanagon check PRs

on: [pull_request_target]

jobs:
 snyk_vanagon:
   runs-on: ubuntu-latest
   steps:
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run Vanagon Snyk Scan
      uses: puppetlabs/security-snyk-vanagon-action@v2.2.0
      with:
        rproxyUser: ${{ secrets.RPROXY_USER }}
        rproxyKey: ${{ secrets.RPROXY_KEY }}
        snykToken: ${{ secrets.SNYK_PE_TOKEN }}
        snykOrg: 'puppet-enterprise'
        skipPlatforms: 'debian-10-armhf'
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1
